### ISSUE TITLE
weekly updates stopped?

### ISSUE THREAD

**Issue by guidohooiveld** [oganm/homologene#18]
Hi,
Small question: maybe I am wrong, but it seems that since June 7 somehow the weekly updates of `homologeneData2` have stopped. Or is a less frequent update schedule implemented now?

Thanks,
Guido

**Comment by oganm** [comment]
Oh thanks for letting me know. I forgot to pull the master to the machine that was running the updates so it couldn't push here. All past updates are pushed now
