### ISSUE TITLE
Add more species in homologene

### ISSUE THREAD

**Issue by KeatsZ** [oganm/homologene#7]
Hi,
I am wondering whether it is possible to add the two modeling species in Plant, Arabidopsis and rice in the homologene package? I find your R package is really convenient to handle large amounts of data.

**Comment by oganm** [comment]
Are the these taxids correct: 4530 for rice and 3702 for arabidopsis? not very familiar with plant taxonomies and there seems to be few species with unique ids and similar names

**Comment by oganm** [comment]
actually nevermind. the other ids don't seem to be in the homologene to begin with. and I will be adding all species since there is no real reason to limit here other than some possible performance issues. it should be fine

**Comment by oganm** [comment]
I was able to add all species as they are from homologene but when trying to compile the homologeneData2 table, I noticed that genes for few species are represented with different taxonomic identifiers. For instance rice genes in homologene appear under different taxonomic identifiers even though on homologene all of them are listed under 4530. Any idea what's happening here?

**Comment by oganm** [comment]
All species are added now. Code below gives all orthologues between rice and Arabidopsis

```r
library(homologene)
library(magrittr)
library(dplyr)
riceIDs = homologeneData %>% filter(Taxonomy == '4530') %$% Gene.ID
homologene(riceIDs, inTax = 4530, outTax = 3702)
```

**Comment by KeatsZ** [comment]
Hi, I have checked the taxID of rice and Arabidopsis in NCBI. The ID of rice is 4530, and that of Arabidopsis is 3702. The reason you find multiple taxID of rice is there are 2 subspecies of rice, Japonica and Indica. The two subspecies have their own taxIDs (Japonica is 39947, and Indica is 39946).
Really thanks for your help!

**Comment by KeatsZ** [comment]
Sorry for disturbing again.  I tried to download the newest version of homologene package, and used the code above to convert rice ID into Arabidopsis ID. However, the console showed “Error in getExportedValue(pkg, name) : lazy-load database 'C:/Users/Zha205/Documents/R/win-library/3.5/homologene/data/Rdata.rdb' is corrupt”.

**Comment by oganm** [comment]
That happens when you Github install an already loaded package. Just restart and you should be fine

**Comment by KeatsZ** [comment]
Yep, the problem was solved after restarted. Thanks!
